using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// ï¿½Gï¿½ï¿½ï¿½_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½ï¿½ó‚¯‚ï¿½ï¿½ï¿½ï¿½p
public class EnemyDamageScript : MonoBehaviour
{
    // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÏXï¿½ï¿½ï¿½Äƒ_ï¿½ï¿½ï¿½[ï¿½Wï¿½Ê‚ğ’²ï¿½
    [SerializeField] private bool isHead = false;
    [SerializeField] private float damageMaltiply = 2.0f; 


    // ï¿½Xï¿½eï¿½[ï¿½^ï¿½Xï¿½ï¿½ï¿½Qï¿½Æ—p
    DefaultEnemyScript enemy;


    // Start is called before the first frame update
    void Start()
    {
        // ï¿½Ïï¿½ï¿½É“Gï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
        if (transform.parent.tag == "RangeEnemy")
        {
            enemy = transform.parent.GetComponentInParent<RangeEnemy>();
        }
        else if (transform.parent.tag == "MeleeEnemy")
        {
            enemy = transform.parent.GetComponentInParent<MeleeEnemyScript>();
        }

    }

    // Update is called once per frame
    void Update()
    {
        
    }

    // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÌUï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½p
    public void HitPlayerAttack(float baseDamage,Vector3 hitPoint)
    {
        // ï¿½ï¿½_ï¿½É“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½
        if (isHead)
        {
            enemy.GetDamage(baseDamage * damageMaltiply,hitPoint);
            enemy.IsStun = true;
        }
        else enemy.GetDamage(baseDamage, hitPoint);

    }
}
